package View;

import Model.Lugar;
import Model.Personagem;
import Model.Termo;

public class ConsultaUI extends javax.swing.JDialog {

    /**
     * Creates new form AlteraTermoUI
     */
    public ConsultaUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        bt_ConsultaRemoveTermo = new javax.swing.JButton();
        lb_AlteraNome = new javax.swing.JLabel();
        tf_AlteraNome = new javax.swing.JTextField();
        bt_ConsultaTermo = new javax.swing.JButton();
        check_AlteraPersonagem = new javax.swing.JRadioButton();
        check_AlteraLugar = new javax.swing.JRadioButton();
        check_AlteraTermo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Termo"));

        bt_ConsultaRemoveTermo.setText("Remover Termo");
        bt_ConsultaRemoveTermo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ConsultaRemoveTermoActionPerformed(evt);
            }
        });

        lb_AlteraNome.setText("Nome:");

        bt_ConsultaTermo.setText("Consultar dados");
        bt_ConsultaTermo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ConsultaTermoActionPerformed(evt);
            }
        });

        buttonGroup1.add(check_AlteraPersonagem);
        check_AlteraPersonagem.setText("Personagem");
        check_AlteraPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_AlteraPersonagemActionPerformed(evt);
            }
        });

        buttonGroup1.add(check_AlteraLugar);
        check_AlteraLugar.setText("Lugar");

        buttonGroup1.add(check_AlteraTermo);
        check_AlteraTermo.setText("Termo Geral");
        check_AlteraTermo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_AlteraTermoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(check_AlteraTermo)
                        .addGap(52, 52, 52)
                        .addComponent(check_AlteraPersonagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(check_AlteraLugar)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_AlteraNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_AlteraNome))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_ConsultaTermo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(bt_ConsultaRemoveTermo)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_AlteraPersonagem)
                    .addComponent(check_AlteraLugar)
                    .addComponent(check_AlteraTermo))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_AlteraNome)
                    .addComponent(tf_AlteraNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ConsultaRemoveTermo)
                    .addComponent(bt_ConsultaTermo))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private Termo jDialogTermo;
    private String acaoTermo;
    private String tipoTermo;
    
    public Termo getJDialogTermo(){
        return jDialogTermo;
    }
    
    public String getAcaoTermo(){
        return acaoTermo;
    }

    public String getTipoTermo() {
        return tipoTermo;
    }
    
    public void obterTermo(){
                
        String nometermo;
        
        nometermo = tf_AlteraNome.getText();
        if(check_AlteraPersonagem.isSelected()){
            jDialogTermo = new Personagem(nometermo);
            tipoTermo = "Personagem";
        }
        else
            if(check_AlteraLugar.isSelected()){
                jDialogTermo = new Lugar(nometermo);
                tipoTermo = "Lugar";
            }
            else{
                jDialogTermo = new Termo(nometermo);
                tipoTermo = "Termo";
            }
    }
    
    private void bt_ConsultaRemoveTermoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ConsultaRemoveTermoActionPerformed
        obterTermo();
        acaoTermo = "Remover";
        dispose();
    }//GEN-LAST:event_bt_ConsultaRemoveTermoActionPerformed

    private void bt_ConsultaTermoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ConsultaTermoActionPerformed
        obterTermo();
        acaoTermo = "Consultar";
        dispose();
    }//GEN-LAST:event_bt_ConsultaTermoActionPerformed

    private void check_AlteraPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_AlteraPersonagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_AlteraPersonagemActionPerformed

    private void check_AlteraTermoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_AlteraTermoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_AlteraTermoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultaUI dialog = new ConsultaUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ConsultaRemoveTermo;
    private javax.swing.JButton bt_ConsultaTermo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton check_AlteraLugar;
    private javax.swing.JRadioButton check_AlteraPersonagem;
    private javax.swing.JRadioButton check_AlteraTermo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_AlteraNome;
    private javax.swing.JTextField tf_AlteraNome;
    // End of variables declaration//GEN-END:variables
}
